--디비버에서 사용해야함 트리거 때문에!!
CREATE TABLE QUESTIONS (-- 질문
	QID INT PRIMARY KEY, -- PK
	LOGIN_ID VARCHAR2(30), -- 작성자 ID
	TITLE VARCHAR2(300) NOT NULL, -- 제목
	ANSWER_A VARCHAR2(300) NOT NULL, -- 답변 A
	ANSWER_B VARCHAR2(300) NOT NULL, -- 답변 B
	EXPLANATION VARCHAR2(300) NOT NULL, -- 문제 설명
	CATEGORY INT DEFAULT 1, -- 카테고리 FK
	Q_ACCESS CHAR(1) DEFAULT 'F' CHECK(Q_ACCESS IN('T','F')) NOT NULL, -- 문제 승인여부
	REG_DATE DATE DEFAULT SYSDATE -- 질문 등록시간
); -- 테이블 합쳐서 칼럼 추가하는 방향으로


CREATE TABLE ANSWERS (-- 답변
	AID INT PRIMARY KEY, -- PK
	QID INT NOT NULL, -- 질문 FK
	LOGIN_ID VARCHAR2(50), -- 로그인 FK
	ANSWER VARCHAR2(300) CHECK(ANSWER IN('A','B')), -- 선택한 답변
	REG_DATE DATE DEFAULT SYSDATE -- 답변 등록시간
);


CREATE TABLE COMMENTS (-- 댓글
	CID INT PRIMARY KEY, -- PK
	QID INT NOT NULL,  -- 질문 FK
	LOGIN_ID VARCHAR2(50), -- 로그인 FK
	CONTENT VARCHAR2(300) NOT NULL,-- 댓글
	REG_DATE DATE DEFAULT SYSDATE -- 댓글 등록시간
);

CREATE TABLE MEMBER ( -- 멤버
    MID INT PRIMARY KEY,-- PK
    LOGIN_ID VARCHAR2(50) UNIQUE NOT NULL, -- 로그인 ID
    MPW VARCHAR2(255) NOT NULL,-- 비밀번호
    NAME VARCHAR2(100) NOT NULL,-- 이름
    CELL_PHONE VARCHAR2(30) NOT NULL, -- 전화번호
    EMAIL VARCHAR2(100) NOT NULL,-- 이메일
    ADDRESS VARCHAR2(1000) NOT NULL,-- 주소
    GENDER VARCHAR2(10) NOT NULL CHECK (GENDER IN ('M', 'F')),-- 성별
    AGE INT NOT NULL,-- 나이
    GRADE INT DEFAULT 1,-- 등급
    MADMIN VARCHAR2(10) DEFAULT 'USER' CHECK (MADMIN IN ('ADMIN', 'USER')),-- 관리자 유무
    REG_DATE DATE DEFAULT SYSDATE-- 유저 등록시간
);

CREATE TABLE SAVE (-- 찜
	SID INT PRIMARY KEY,-- PK
	QID INT , -- 질문 FK
	LOGIN_ID VARCHAR2(50)-- 로그인 FK
);

CREATE TABLE SUPPORT (--후원
	SUID INT PRIMARY KEY,-- PK
	LOGIN_ID VARCHAR2(50),-- 로그인 FK
	AMOUNT INT NOT NULL,-- 후원금액
	REG_DATE DATE DEFAULT SYSDATE-- 후원 등록시간
);

--카테고리 정규화
CREATE TABLE CATEGORY(--카테고리
	CGID INT PRIMARY KEY,-- PK
	CATEGORY VARCHAR2(300) NOT NULL
);

CREATE TABLE SUGGESTION(--건의
	SUGID INT PRIMARY KEY,--건의 PK
	LOGIN_ID VARCHAR2(50), --로그인 아이디
	TITLE VARCHAR2(50), --제목
	SUGGESTION VARCHAR2(4000),--건의사항
	REG_DATE DATE DEFAULT SYSDATE--건의 등옥시간
);
--트리거 삽입

--후원 트리거
CREATE OR REPLACE TRIGGER SUM_SUPPORT_TRIGGER
BEFORE INSERT ON TEEMO.SUPPORT
FOR EACH ROW
DECLARE
    TOTAL NUMBER;
BEGIN
    IF INSERTING THEN
-- 사용자의 총 후원금액 계산
SELECT NVL(SUM(AMOUNT), 0) + :NEW.AMOUNT INTO TOTAL FROM TEEMO.SUPPORT WHERE LOGIN_ID = :NEW.LOGIN_ID;

-- 사용자 등급 조정
        UPDATE TEEMO.MEMBER
        SET GRADE = CASE
                        WHEN TOTAL >= 1000000 THEN 4
                        WHEN TOTAL >= 100000 THEN 3
                        WHEN TOTAL >= 10000 THEN 2
                        ELSE GRADE
                    END
        WHERE LOGIN_ID = :NEW.LOGIN_ID;

-- 후원금액 출력
        DBMS_OUTPUT.PUT_LINE('AMOUNT: ' || TOTAL);
    END IF;

EXCEPTION
    WHEN OTHERS THEN
-- 예외 처리
        DBMS_OUTPUT.PUT_LINE('Exception: ' || SQLERRM);
-- 롤백을 수행할 수 있음
	ROLLBACK;
END SUM_SUPPORT_TRIGGER;


--유저 삭제
CREATE OR REPLACE TRIGGER USER_DELETE_TRIGGER
BEFORE DELETE ON TEEMO.MEMBER--삭제가 발생하면
FOR EACH ROW
BEGIN--다른 테이블 LOGIN_ID를 null로 UPDATE
   UPDATE TEEMO.QUESTIONS  SET LOGIN_ID = NULL WHERE LOGIN_ID = :OLD.LOGIN_ID;
   UPDATE TEEMO.ANSWERS  SET LOGIN_ID = NULL WHERE LOGIN_ID = :OLD.LOGIN_ID;
   UPDATE TEEMO.COMMENTS  SET LOGIN_ID = NULL WHERE LOGIN_ID = :OLD.LOGIN_ID;
   UPDATE TEEMO.SAVE  SET LOGIN_ID = NULL WHERE LOGIN_ID = :OLD.LOGIN_ID;
   UPDATE TEEMO.SUPPORT  SET LOGIN_ID = NULL WHERE LOGIN_ID = :OLD.LOGIN_ID;
   UPDATE TEEMO.SUGGESTION  SET LOGIN_ID = NULL WHERE LOGIN_ID = :OLD.LOGIN_ID;
EXCEPTION
    WHEN OTHERS THEN
-- 예외 처리
        DBMS_OUTPUT.PUT_LINE('Exception: ' || SQLERRM);
-- 롤백을 수행할 수 있음ROLLBACK;
END USER_DELETE_TRIGGER;

-- 샘플 데이터 삽입
INSERT ALL
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE) VALUES (1, 'user', '1234', '홍길동', 'user@example.com', '010-1234-5645', '서울시 강남', 'M', 30)
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE) VALUES (2, 'user1', 'password1', '홍길동', 'user1@example.com', '010-1234-5678', '서울시 강남구', 'M', 30)
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE) VALUES (3, 'user2', 'password2', '김영희', 'user2@example.com', '010-9876-5432', '서울시 종로구', 'F', 25)
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE) VALUES (4, 'user3', 'password3', '박철수', 'user3@example.com', '010-1111-2222', '서울시 강남구', 'M', 30)
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE) VALUES (5, 'user4', 'password4', '이미경', 'user4@example.com', '010-3333-4444', '서울시 서초구', 'F', 22)
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE) VALUES (6, 'user5', 'password5', '김태영', 'user5@example.com', '010-5555-6666', '서울시 강북구', 'M', 35)
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE) VALUES (7, 'user6', 'password6', '정다운', 'user6@example.com', '010-7777-8888', '서울시 송파구', 'F', 28)
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE) VALUES (8, 'user7', 'password7', '장선우', 'user7@example.com', '010-9999-0000', '서울시 중랑구', 'M', 24)
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE) VALUES (9, 'user8', 'password8', '이현주', 'user8@example.com', '010-1234-5678', '서울시 강서구', 'F', 31)
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE) VALUES (10, 'user9', 'password9', '김철민', 'user9@example.com', '010-3456-7890', '서울시 강동구', 'M', 27)
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE) VALUES (11, 'user10', 'password10', '신지영', 'user10@example.com', '010-9876-5432', '서울시 마포구', 'F', 29)
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE) VALUES (12, 'user11', 'password11', '배민수', 'user11@example.com', '010-1111-2222', '서울시 강남구', 'M', 33)
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE) VALUES (13, 'user12', 'password12', '이수지', 'user12@example.com', '010-3333-4444', '서울시 강북구', 'F', 26)
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE) VALUES (14, 'user13', 'password13', '최민수', 'user13@example.com', '010-5555-6666', '서울시 송파구', 'M', 34)
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE) VALUES (15, 'user14', 'password14', '정다은', 'user14@example.com', '010-7777-8888', '서울시 서초구', 'F', 27)
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE) VALUES (16, 'user15', 'password15', '이준호', 'user15@example.com', '010-9999-0000', '서울시 중랑구', 'M', 25)
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE) VALUES (17, 'user16', 'password16', '장윤서', 'user16@example.com', '010-1234-5678', '서울시 강서구', 'F', 30)
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE) VALUES (18, 'user17', 'password17', '이승호', 'user17@example.com', '010-3456-7890', '서울시 강동구', 'M', 22)
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE) VALUES (19, 'user18', 'password18', '김지영', 'user18@example.com', '010-9876-5432', '서울시 마포구', 'F', 28)
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE) VALUES (20, 'user19', 'password19', '박준호', 'user19@example.com', '010-1111-2222', '서울시 강남구', 'M', 32)
INTO MEMBER (MID, LOGIN_ID, MPW, NAME, EMAIL, CELL_PHONE, ADDRESS, GENDER, AGE, MADMIN) VALUES (21, 'admin', '1234', '김다은', 'user20@example.com', '010-3333-4444', '서울시 강북구', 'F', 29,'ADMIN')
INTO CATEGORY VALUES(1,'전체이용가')
INTO CATEGORY VALUES(2,'19금')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(1,1,'user1','문제 좋은데?')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(2,1,'user2','이건 당연히 후자이지')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(3,1,'user4','뭔솔? 당연히 전자이지')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(4,1,'user5','에혀 또 싸우네')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(5,1,'user6','불고기 만드는 방법...')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(6,1,'user7','옌 어디에나 있네')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(7,2,'user1','문제 좋은데?')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(8,2,'user2','이건 당연히 전자이지')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(9,2,'user8','싸우자')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(10,2,'user6','불고기 만드는 방법...')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(11,3,'user9','1빠다')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(12,3,'user14','2')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(13,3,'user6','불고기 만드는 방법...')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(14,4,'user6','불고기 만드는 방법...')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(15,5,'user14','졸려')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(16,5,'user20','코로나 이 녀석!')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(17,6,'user10','자 과연')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(18,6,'user11','난 2번')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(19,7,'user18','대박')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(20,7,'user16','이건 못 골라')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(21,8,'user17','좋은데?')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(22,8,'user15','가자')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(23,9,'user13','이걸 못골라?')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(24,9,'user12','못고르겠는데?')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(25,10,'user7','인정합니다')
INTO COMMENTS (CID,QID,LOGIN_ID,CONTENT) VALUES(26,10,'user19','출제자 너무 하네')
INTO SUGGESTION(SUGID,LOGIN_ID,TITLE,SUGGESTION) VALUES(1,'user1','이건 아니지 않나','문제 마음에 드네요 ♥')
INTO SUGGESTION(SUGID,LOGIN_ID,TITLE,SUGGESTION) VALUES(2,'user2','냐미','관리점')
INTO SUGGESTION(SUGID,LOGIN_ID,TITLE,SUGGESTION) VALUES(3,'user3','음 좋은데?','문제 더 줘')
INTO SUGGESTION(SUGID,LOGIN_ID,TITLE,SUGGESTION) VALUES(4,'user4','그맛','로아 사랑')
INTO SUGGESTION(SUGID,LOGIN_ID,TITLE,SUGGESTION) VALUES(5,'user5','메이플 하지져?','메이플 한하면 간첩인데')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(1,1,'user1','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(2,1,'user2','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(3,1,'user3','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(4,1,'user4','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(5,1,'user5','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(6,1,'user6','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(7,1,'user7','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(8,1,'user8','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(9,1,'user9','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(10,1,'user10','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(11,1,'user11','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 12,1,'user12','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 13,2,'user1','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 14,2,'user2','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 15,2,'user3','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 16,2,'user4','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 17,2,'user5','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 18,2,'user6','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 19,2,'user7','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 20,2,'user8','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 21,2,'user9','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 22,2,'user10','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 23,2,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 24,2,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 25,3,'user1','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 26,3,'user2','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 27,3,'user3','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 28,3,'user4','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 29,3,'user5','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 30,3,'user6','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 31,3,'user7','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 32,3,'user8','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 33,3,'user9','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 34,3,'user10','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 35,3,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 36,3,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 37,4,'user1','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 38,4,'user2','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 39,4,'user3','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 40,4,'user4','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 41,4,'user5','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 42,4,'user6','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 43,4,'user7','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 44,4,'user8','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 45,4,'user9','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 46,4,'user10','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 47,4,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 48,4,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 49,5,'user1','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 50,5,'user2','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 51,5,'user3','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 52,5,'user4','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 53,5,'user5','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 54,5,'user6','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 55,5,'user7','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 56,5,'user8','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 57,5,'user9','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 58,5,'user10','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 59,5,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 60,5,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 61,6,'user1','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 62,6,'user2','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 63,6,'user3','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 64,6,'user4','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 65,6,'user5','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 66,6,'user6','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 67,6,'user7','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 68,6,'user8','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 69,6,'user9','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 70,6,'user10','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 71,6,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 72,6,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 73,7,'user1','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 74,7,'user2','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 75,7,'user3','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 76,7,'user4','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 77,7,'user5','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 78,7,'user6','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 79,7,'user7','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 80,7,'user8','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 81,7,'user9','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 82,7,'user10','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 83,7,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 84,7,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 85,8,'user1','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 86,8,'user2','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 87,8,'user3','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 88,8,'user4','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 89,8,'user5','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 90,8,'user6','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 91,8,'user7','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 92,8,'user8','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 93,8,'user9','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 94,8,'user10','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 95,8,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 96,8,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 97,9,'user1','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 98,9,'user2','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 99,9,'user3','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 100,9,'user4','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 101,9,'user5','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 102,9,'user6','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 103,9,'user7','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 104,9,'user8','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 105,9,'user9','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 106,9,'user10','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 107,9,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 108,9,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 109,10,'user1','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 110,10,'user2','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 111,10,'user3','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 112,10,'user4','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 113,10,'user5','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 114,10,'user6','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 115,10,'user7','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 116,10,'user8','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 117,10,'user9','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES( 118,10,'user10','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(119,10,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(120,10,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(121,11,'user1','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(122,11,'user2','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(123,11,'user3','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(124,11,'user4','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(125,11,'user5','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(126,11,'user6','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(127,11,'user7','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(128,11,'user8','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(129,11,'user9','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(130,11,'user10','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(131,11,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(132,11,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(133,12,'user1','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(134,12,'user2','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(135,12,'user3','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(136,12,'user4','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(137,12,'user5','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(138,12,'user6','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(139,12,'user7','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(140,12,'user8','B')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(141,12,'user9','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(142,12,'user10','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(143,12,'user11','A')
INTO ANSWERS (AID,QID,LOGIN_ID,ANSWER)VALUES(144,12,'user11','A')
SELECT * FROM DUAL;



INSERT INTO SUPPORT (SUID,LOGIN_ID,AMOUNT) VALUES (1,'user1','100000');
INSERT INTO SUPPORT (SUID,LOGIN_ID,AMOUNT) VALUES (2,'user2','1000000');
INSERT INTO SUPPORT (SUID,LOGIN_ID,AMOUNT) VALUES (3,'user3','1234');
INSERT INTO SUPPORT (SUID,LOGIN_ID,AMOUNT) VALUES (4,'user4','1004');
